// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5ZCj9iP2pJZcta5nzMGH42u3-KDSDtU',
    appId: '1:1011725601547:web:c36cec3963fef90a83300e',
    messagingSenderId: '1011725601547',
    projectId: 'absensi-siswa-9d7cf',
    authDomain: 'absensi-siswa-9d7cf.firebaseapp.com',
    storageBucket: 'absensi-siswa-9d7cf.appspot.com',
    measurementId: 'G-1KR2QD0XE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPqBqbc0ZltfDoD3bTwcNn4vH6wnAxz0U',
    appId: '1:1011725601547:android:ab82f3eeefa6af5383300e',
    messagingSenderId: '1011725601547',
    projectId: 'absensi-siswa-9d7cf',
    storageBucket: 'absensi-siswa-9d7cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqIy-ozpekdBkeLeAsaE5CjEQEjh3lj6I',
    appId: '1:1011725601547:ios:d379c6693cf76faf83300e',
    messagingSenderId: '1011725601547',
    projectId: 'absensi-siswa-9d7cf',
    storageBucket: 'absensi-siswa-9d7cf.appspot.com',
    iosBundleId: 'com.example.absensiSiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqIy-ozpekdBkeLeAsaE5CjEQEjh3lj6I',
    appId: '1:1011725601547:ios:0c65194e7f25f44383300e',
    messagingSenderId: '1011725601547',
    projectId: 'absensi-siswa-9d7cf',
    storageBucket: 'absensi-siswa-9d7cf.appspot.com',
    iosBundleId: 'com.example.absensiSiswa.RunnerTests',
  );
}
